---
- name: Install Apache for servers Playbook
  hosts: SERVERS
  become: yes


  tasks:

  - name: Check the OS
    debug: 
      var: ansible_os_family

  - block:       #---REDHAT---

      - name: Install Apache WebServer on RedHat
        yum: 
          name: httpd
          state: latest

      - name: Start Apache WebServer on RedHat
        service:
          name: httpd
          state: started
          enabled: yes

    when: ansible_os_family == "RedHat"


  - block:       #---UBUNTU---

      - name: Install Apache WebServer on Ubuntu
        apt:
          name: apache2
          state: latest

      - name: Start Apache WebServer on Ubuntu
        service:
          name: apache2
          state: started
          enabled: yes

    when: ansible_os_family == "Debian"

...
